ADD: Se agregan cambios para Vista de Detalle.
Architect-Coders/ArtApp pull request #18
Opened 2019-11-27 19:17 UTC by Ivan93Vixtra

Creacion de vista detalle, faltaria la llamada de mainActivity a detalle y pasar por bundle elemento Coverphoto.

2019-11-27 20:39 UTC, yeho commented on app/src/main/res/layout/activity_detail_art.xml
> +                android:layout_height="250dp"
para no quitarle protagonismo a la imagen aqui le aumentaria el tamaño del collapsingtoolbar
```suggestion
                android:layout_height="450dp"
```

2019-11-27 21:19 UTC, yeho commented
LGTM

2019-12-03 04:27 UTC, DjangoLC commented
Me parece bien, solo resolver conflictos y esta listo para merge en develop

2019-12-03 04:28 UTC, DjangoLC requested changes
Me parece bien, solo resolver conflictos y esta listo para merge en develop

2019-12-05 19:33 UTC, DjangoLC approved these changes
Listo para dev

2019-12-06 02:59 UTC, merged